update

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,4 +1,3 @@
-# this is needed for container_scanning and internal to gitlab yml
 include:
   - template: Jobs/Container-Scanning.gitlab-ci.yml
 
@@ -15,7 +14,9 @@ default:
     paths:
       - build/libs/* 
       - ocp/* 
-    expire_in: 3h    
+    expire_in: 3h  
+    reports:
+      dotenv: variables.env    
 
 variables:
   NAMESPACE: gitlab-qa
@@ -65,8 +66,8 @@ build-app: # build application
         [[ -f $JAR_FOLDER/$GRADLE_NAME-$GRADLE_VERSION.war ]] && echo "GRADLE_EXT=war" >>$JAR_FOLDER/build.env \
         && export GRADLE_EXT=war 
       fi
-      if [[ "$GRADLE_EXT" == "" ]]; then echo "Cannot determine the file extension!" && exit 1; fi        
-
+      if [[ "$GRADLE_EXT" == "" ]]; then echo "Cannot determine the file extension!" && exit 1; fi 
+      
 scan-sonarqube: # scan with sonarqube
   stage: test
   variables:
@@ -90,9 +91,10 @@ scan-sonarqube: # scan with sonarqube
     - | # run sonarqube scan
       gradle sonarqube
 
+
 build-docker: # build docker image
   stage: build-docker
-  image: $REGISTRY/openshift/origin-cli:latest
+  image: docker.io/openshift/origin-cli:latest
   dependencies:
     - scan-sonarqube
   script:
@@ -132,13 +134,10 @@ build-docker: # build docker image
       # save credentail for helm use
       cp $KUBECONFIG $HOME/ocp/   
     - | # execute rbac-helm
-      oc apply -f ocp/build/rbac-helm.yaml  
-    - | # save GRADLE_NAME for container_scanning
-      echo "GRADLE_NAME=$GRADLE_NAME" > variables.env # work with container_scanning       
-  artifacts:
-    reports:
-      dotenv: variables.env # this is the only one that work with container_scanning    
-
+      oc apply -f ocp/build/rbac-helm.yaml   
+    - | # for container_scanning to get $GRADLE_NAME
+      echo "GRADLE_NAME=$GRADLE_NAME" > variables.env       
+  
 container_scanning:
   stage: scan-image  
   needs:
